// <auto-generated />
using System;
using InvestimentosCaixa.Api.Infraestrutura.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestimentosCaixa.Api.Migrations
{
    [DbContext(typeof(InvestimentosCaixaDbContext))]
    [Migration("20251117013725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("InvestimentosCaixa.Api.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Liquidez")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("InvestimentosCaixa.Api.Dominio.Entidades.Investimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProduto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdProduto");

                    b.ToTable("Investimentos");
                });

            modelBuilder.Entity("InvestimentosCaixa.Api.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rentabilidade")
                        .HasColumnType("TEXT");

                    b.Property<int>("Risco")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("InvestimentosCaixa.Api.Dominio.Entidades.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProduto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorInvestido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdProduto");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("InvestimentosCaixa.Api.Dominio.Entidades.Telemetria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeRota")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TempoResposta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Telemetrias");
                });

            modelBuilder.Entity("InvestimentosCaixa.Api.Dominio.Entidades.Investimento", b =>
                {
                    b.HasOne("InvestimentosCaixa.Api.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("Investimentos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestimentosCaixa.Api.Dominio.Entidades.Produto", "Produto")
                        .WithMany("Investimentos")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("InvestimentosCaixa.Api.Dominio.Entidades.Simulacao", b =>
                {
                    b.HasOne("InvestimentosCaixa.Api.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("Simulacoes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestimentosCaixa.Api.Dominio.Entidades.Produto", "Produto")
                        .WithMany("Simulacoes")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("InvestimentosCaixa.Api.Dominio.Entidades.Cliente", b =>
                {
                    b.Navigation("Investimentos");

                    b.Navigation("Simulacoes");
                });

            modelBuilder.Entity("InvestimentosCaixa.Api.Dominio.Entidades.Produto", b =>
                {
                    b.Navigation("Investimentos");

                    b.Navigation("Simulacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
